[package]
name = "app"
version = "0.1.0"
edition.workspace = true

[dependencies]
core = { workspace = true }
macroquad = { workspace = true }
taffy = "0.9.2"
serde = { workspace = true }
serde_json = { workspace = true }
directories = "5.0"
tempfile = "3.10"

[lints]
workspace = true
