[package]
name = "core"
version = "0.1.0"
edition.workspace = true

[dependencies]
rand_chacha = { workspace = true }
slotmap = { workspace = true }
xxhash-rust = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
proptest = "1.10.0"

[lints]
workspace = true
